### config.yaml

# mqtt connection
mqtt_broker: 192.168.5.113

# serial connection
serial_device: /dev/ttyUSB0
serial_speed: 9600

# status
status:
  topic: paradox/status
  message_connect: online
  message_disconnect: offline

message_mapping:
  # alarm panel
  - bytes: [0x3c, 0x11]
    topic: paradox/alarm_panel
    message: disarmed
  - bytes: [0x40, 0x11]
    topic: paradox/alarm_panel
    message: disarmed
  - bytes: [0x34, 0x11]
    topic: paradox/alarm_panel
    message: armed_away
  - bytes: [0x50, 0x11]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x21]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x31]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x41]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x51]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x61]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x71]
    topic: paradox/alarm_panel
    message: triggered
  - bytes: [0x50, 0x81]
    topic: paradox/alarm_panel
    message: triggered

    # contacts
  - bytes: [0x04, 0x11]
    topic: paradox/contacts/1
    message: ON
  - bytes: [0x00, 0x11]
    topic: paradox/contacts/1
    message: OFF
  - bytes: [0x04, 0x21]
    topic: paradox/contacts/2
    message: ON
  - bytes: [0x00, 0x21]
    topic: paradox/contacts/2
    message: OFF
  - bytes: [0x04, 0x31]
    topic: paradox/contacts/3
    message: ON
  - bytes: [0x00, 0x31]
    topic: paradox/contacts/3
    message: OFF
  - bytes: [0x04, 0x41]
    topic: paradox/contacts/4
    message: ON
  - bytes: [0x00, 0x41]
    topic: paradox/contacts/4
    message: OFF
  - bytes: [0x04, 0x51]
    topic: paradox/contacts/5
    message: ON
  - bytes: [0x00, 0x51]
    topic: paradox/contacts/5
    message: OFF
  - bytes: [0x04, 0x61]
    topic: paradox/contacts/6
    message: ON
  - bytes: [0x00, 0x61]
    topic: paradox/contacts/6
    message: OFF
  - bytes: [0x04, 0x71]
    topic: paradox/contacts/7
    message: ON
  - bytes: [0x00, 0x71]
    topic: paradox/contacts/7
    message: OFF
  - bytes: [0x04, 0x81]
    topic: paradox/contacts/8
    message: ON
  - bytes: [0x00, 0x81]
    topic: paradox/contacts/8
    message: OFF
